neo4j: 
    host: 'localhost'
    port: '7687'
    scheme: 'bolt'
    user: 'neo4j'
    password: 'password'
    secure: False

mongodb:
    database_name: 'collaborator_entity_info'
    host: localhost
    port: 27017
    username: NULL 
    password: NULL

